on:
  workflow_run:
    workflows:
      - Docker
    types:
      - completed

name: Prepare Staging
jobs:
  prep-staging:
    name: Prepare Staging Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment vars
        run: |
          source dev/image.env
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "BRANCH=release-staging-$IMAGE_TAG" >> $GITHUB_ENV
          git config user.name Russ Parmer
          git config user.email rparmer02@gmail.com
      - name: Update Staging Image Tag
        run: |
          git checkout -b "$BRANCH"
          cp dev/image.env staging/image.env
          git add staging/image.env
          git commit -m "Update staging image to $IMAGE_TAG"
          git push -u origin "$BRANCH"
      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.pulls.create({
              title: 'Update staging image tag to ${{ env.IMAGE_TAG }}',
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: '${{ env.BRANCH }}',
              base: 'main'
            });
