name: release-staging

on:
  workflow_dispatch:
  push:
    branches: [release]
    paths:
      - 'dev/**'

jobs:
  release-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: release
      - name: Set up environment vars
        run: |
          source dev/image.env
          echo "RELEASE=$IMAGE_TAG" >> $GITHUB_ENV
          echo "BRANCH=release-staging-$IMAGE_TAG" >> $GITHUB_ENV
          git config user.name Russ Parmer
          git config user.email rparmer02@gmail.com
      - name: Release
        id: release
        run: |
          if [[ ${{ env.RELEASE }} =~ ^v[0-9]+.[0-9]+.[0-9]+ ]]; then
            echo ::set-output name=release::true
          fi
      - name: Update Staging Image Tag
        if: steps.release.outputs.release == 'true'
        run: |
          git checkout -b "$BRANCH"
          cp dev/app.yaml staging/app.yaml
          cp dev/image.env staging/image.env
          git add staging/app.yaml staging/image.env
          git diff-index --quiet HEAD || git commit -m "Release $RELEASE to staging"
          git push -u origin "$BRANCH"
      - name: Create Pull Request
        if: steps.release.outputs.release == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.pulls.create({
              title: 'Release ${{ env.RELEASE }} to staging',
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: '${{ env.BRANCH }}',
              base: 'release'
            });
