name: release-prod

on:
  push:
    branches: [release]
    paths:
      - 'staging/**'

jobs:
  release-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: release
      - name: Set up environment vars
        run: |
          source staging/image.env
          echo "RELEASE=$IMAGE_TAG" >> $GITHUB_ENV
          echo "BRANCH=release-prod-$IMAGE_TAG" >> $GITHUB_ENV
          git config user.name Russ Parmer
          git config user.email rparmer02@gmail.com
      - name: Release
        id: release
        run: |
          if [[ ${{ env.RELEASE }} =~ ^v[0-9]+.[0-9]+.[0-9]+ ]]; then
            echo ::set-output name=release::true
          fi
      - name: Update Staging Image Tag
        if: steps.release.outputs.release == 'true'
        run: |
          git checkout -b "$BRANCH"
          cp staging/app.yaml prod/app.yaml
          cp staging/image.env prod/image.env
          git add prod/app.yaml prod/image.env
          git diff-index --quiet HEAD || git commit -m "Release $RELEASE to prod"
          git push -u origin "$BRANCH"
      - name: Create Pull Request
        if: steps.release.outputs.release == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.pulls.create({
              title: 'Release ${{ env.RELEASE }} to prod',
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: '${{ env.BRANCH }}',
              base: 'release'
            });
